spring.application.name=sistema-hospitalar
# Configuração H2
spring.datasource.url=jdbc:h2:mem:hospitaldb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console habilitado para visualizarmos o banco no navegador
spring.h2.console.enabled=true

# Hibernate vai gerar as tabelas automaticamente baseadas nas nossas classes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true